# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './python/ui/dialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(501, 125)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.textAddress.setObjectName("textAddress")
        self.verticalLayout.addWidget(self.textAddress)
        self.textPrivateKey = QtWidgets.QLineEdit(self.centralwidget)
        self.textPrivateKey.setObjectName("textPrivateKey")
        self.verticalLayout.addWidget(self.textPrivateKey)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLogin.setObjectName("buttonLogin")
        self.verticalLayout.addWidget(self.buttonLogin)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.textAddress.setPlaceholderText(_translate("LoginWindow", "Address"))
        self.textPrivateKey.setPlaceholderText(_translate("LoginWindow", "Private Key"))
        self.buttonLogin.setText(_translate("LoginWindow", "Login"))
