# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\python\ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 791, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tabLogin = QtWidgets.QWidget()
        self.tabLogin.setObjectName("tabLogin")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabLogin)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.textAddress = QtWidgets.QLineEdit(self.tabLogin)
        self.textAddress.setObjectName("textAddress")
        self.verticalLayout.addWidget(self.textAddress)
        self.textPrivateKey = QtWidgets.QLineEdit(self.tabLogin)
        self.textPrivateKey.setObjectName("textPrivateKey")
        self.verticalLayout.addWidget(self.textPrivateKey)
        self.label = QtWidgets.QLabel(self.tabLogin)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonLogin = QtWidgets.QPushButton(self.tabLogin)
        self.buttonLogin.setObjectName("buttonLogin")
        self.verticalLayout.addWidget(self.buttonLogin)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabLogin, "")
        self.tabAdmin = QtWidgets.QWidget()
        self.tabAdmin.setEnabled(True)
        self.tabAdmin.setObjectName("tabAdmin")
        self.tabWidget.addTab(self.tabAdmin, "")
        self.tabWorker = QtWidgets.QWidget()
        self.tabWorker.setEnabled(True)
        self.tabWorker.setObjectName("tabWorker")
        self.tabWidget.addTab(self.tabWorker, "")
        self.tabClient = QtWidgets.QWidget()
        self.tabClient.setEnabled(True)
        self.tabClient.setObjectName("tabClient")
        self.tabWidget.addTab(self.tabClient, "")
        self.tabServices = QtWidgets.QWidget()
        self.tabServices.setObjectName("tabServices")
        self.tableServices = QtWidgets.QTableWidget(self.tabServices)
        self.tableServices.setGeometry(QtCore.QRect(0, 0, 791, 511))
        self.tableServices.setObjectName("tableServices")
        self.tableServices.setColumnCount(0)
        self.tableServices.setRowCount(0)
        self.tabWidget.addTab(self.tabServices, "")
        self.buttonRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRefresh.setGeometry(QtCore.QRect(700, 20, 75, 23))
        self.buttonRefresh.setObjectName("buttonRefresh")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textAddress.setPlaceholderText(_translate("MainWindow", "Address"))
        self.textPrivateKey.setPlaceholderText(_translate("MainWindow", "Private Key"))
        self.buttonLogin.setText(_translate("MainWindow", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogin), _translate("MainWindow", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdmin), _translate("MainWindow", "Admin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWorker), _translate("MainWindow", "Worker"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClient), _translate("MainWindow", "Client"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServices), _translate("MainWindow", "Services"))
        self.buttonRefresh.setText(_translate("MainWindow", "Refresh"))
